---
title: "Analysis"
output: html_document
---



## Metabolite analysis

```{r echo =FALSE,message=FALSE, warning=FALSE}
library(reshape2)
library(ggplot2)
library(plotly)
library(matrixStats)
#setwd('/Users/kumaran/linuxshare/con_analysis/')
m<-read.csv('con2.csv',header = T,check.names = FALSE)
row.names(m)<-m$Name
m[1]<-NULL
b6lean<-m[c(1,2,3,4,5,6,7),]
b6ob<-m[c(8,9,10,11,12,13),]
b6<-m[c(1,2,3,4,5,6,7,8,9,10,11,12,13),]
btbrlean<-m[c(14,15,16,17,18),]
btbrob<-m[c(19,20,21,22,23,24),]
btbr<-m[c(14,15,16,17,18,19,20,21,22,23,24),]
lean<-m[c(1,2,3,4,5,6,7,14,15,16,17,18),]
obes<-m[c(8,9,10,11,12,13,19,20,21,22,23,24),]
all<-m
matrix_mean<-function(m,label){
  m[row(m)==col(m)]<-0.0
  mn<-as.data.frame(rowMeans(m))
  colnames(mn)[1]="mean"
  mn$metabolites=rownames(mn)
  mn$sd<-rowSds(m)
  rownames(mn)<-NULL
  mn$dataset=label
  return(mn)
}

compare_matrix_mean<-function(m1,m2){
  mm<-merge(m1,m2,by=c('metabolites'))
  mm$meandiff<-mm$mean.x-mm$mean.y
  mm$dataset<-paste(mm$dataset.x,mm$dataset.y)
  mmdat<-subset(mm,select=c("metabolites","meandiff","dataset"))
  return(mmdat)
}
  
ratio_matix<-function(m,n){
  df<-as.vector(t(m[c(n),]))
  mm<-log(outer(df,df,"/"))
  colnames(mm)<-colnames(m)
  rownames(mm)<-colnames(m)
  return(mm)
}
plt_matrix<-function(m){
  m2<-melt(m)
  plt<-ggplot2::ggplot(m2)+ggplot2::geom_tile(aes(x=Var1,y=Var2,fill=as.numeric(value)))+
    ggplot2::scale_fill_gradient2(low = "blue", high = "red", mid = "white",
                                  midpoint = 0, limit = c(min(m2$value),max(m2$value)), space = "Lab",name="Log Ratio")+
    ggplot2::theme(axis.text.x = element_text(angle = 90, hjust = 1,vjust = 0.5))+
    ggplot2::xlab("")+ggplot2::ylab("")
  plt1<-plotly::ggplotly(plt)
  return(plt1)
}

rb6l<-(ratio_matix(m,1)+ratio_matix(m,2)+ratio_matix(m,3)+ratio_matix(m,4)+ratio_matix(m,5)+ratio_matix(m,6)+ratio_matix(m,7))/7
rb6o<-(ratio_matix(m,8)+ratio_matix(m,9)+ratio_matix(m,10)+ratio_matix(m,11)+ratio_matix(m,12)+ratio_matix(m,13))/6
rbtbrl<-(ratio_matix(m,14)+ratio_matix(m,15)+ratio_matix(m,16)+ratio_matix(m,17)+ratio_matix(m,18))/5
rbtbro<-(ratio_matix(m,19)+ratio_matix(m,20)+ratio_matix(m,21)+ratio_matix(m,22)+ratio_matix(m,23)+ratio_matix(m,24))/6
rb6<-(ratio_matix(m,1)+ratio_matix(m,2)+ratio_matix(m,3)+ratio_matix(m,4)+ratio_matix(m,5)+ratio_matix(m,6)+ratio_matix(m,7)+ratio_matix(m,8)+ratio_matix(m,9)+ratio_matix(m,10)+ratio_matix(m,11)+ratio_matix(m,12)+ratio_matix(m,13))/13
rbtbr<-(ratio_matix(m,14)+ratio_matix(m,15)+ratio_matix(m,16)+ratio_matix(m,17)+ratio_matix(m,18)+ratio_matix(m,19)+ratio_matix(m,20)+ratio_matix(m,21)+ratio_matix(m,22)+ratio_matix(m,23)+ratio_matix(m,24))/11
rlean<-(ratio_matix(m,1)+ratio_matix(m,2)+ratio_matix(m,3)+ratio_matix(m,4)+ratio_matix(m,5)+ratio_matix(m,6)+ratio_matix(m,7)+ratio_matix(m,14)+ratio_matix(m,15)+ratio_matix(m,16)+ratio_matix(m,17)+ratio_matix(m,18))/12
robes<-(ratio_matix(m,8)+ratio_matix(m,9)+ratio_matix(m,10)+ratio_matix(m,11)+ratio_matix(m,12)+ratio_matix(m,13)+ratio_matix(m,19)+ratio_matix(m,20)+ratio_matix(m,21)+ratio_matix(m,22)+ratio_matix(m,23)+ratio_matix(m,24))/12


allm<-round(cor(all),4)
b6m<-round(cor(b6),4)
btbrm<-round(cor(btbr),4)
leanm<-round(cor(lean),4)
obesm<-round(cor(obes),4)
b6leanm<-round(cor(b6lean),4)
b6obm<-round(cor(b6ob),4)
btbrleanm<-round(cor(btbrlean),4)
btbrobm<-round(cor(btbrob),4)
```

### Cross correlation method

You can view the cross correlation matrices and cross correlation difference matrices for each gorup from the pull down menu on the top. 

### Interpretation of results

The second plot (mean correlation difference) on the result page give the information about metabolite activity. 

For example : Mannitol

* BTBR vs BRBR Lean -1.15 (strong signal)
* BTBR Lean vs BRBR Obesity 1.03 (strong signal)
* BRBR vs BRBR Obesity -0.13 (weak signal)

Lese see what the Mean coorelation within each group

* BTBR -0.34
* BTBR Lean 0.81
* BTBR Obesity -0.21

The means Mannitol has good positive porrelation in BRBR Lean group, which means on average Minnitol concentration increases as rest of the metabolite concentration increases. This is not true in BRBR Obesity group. This can be easily verified by looling at the correlation matrix and comparison matrix(avilable from the pull down menu)


